name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install
        working-directory: ./user-service

      - name: Run tests
        run: npm test
        working-directory: ./user-service

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service ./user-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service ./order-service

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service

      - name: Deploy containers
        run: |
          docker stop user-service || true
          docker rm user-service || true
          docker stop order-service || true
          docker rm order-service || true
          docker run -d --name user-service -p 5001:5001 ${{ secrets.DOCKER_USERNAME }}/user-service
          docker run -d --name order-service -p 5002:5002 ${{ secrets.DOCKER_USERNAME }}/order-service
